/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coi_tools_os_izpack_COIOSHelper */

#ifndef _Included_com_coi_tools_os_izpack_COIOSHelper
#define _Included_com_coi_tools_os_izpack_COIOSHelper
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: self */
/* Inaccessible static: used */
/*
 * Class:     com_coi_tools_os_izpack_COIOSHelper
 * Method:    FreeLibrary
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_izpack_COIOSHelper_FreeLibrary
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
