/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coi_tools_os_win_RegistryImpl */

#ifndef _Included_com_coi_tools_os_win_RegistryImpl
#define _Included_com_coi_tools_os_win_RegistryImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_coi_tools_os_win_RegistryImpl_HKEY_CLASSES_ROOT
#define com_coi_tools_os_win_RegistryImpl_HKEY_CLASSES_ROOT -2147483648L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_CURRENT_USER
#define com_coi_tools_os_win_RegistryImpl_HKEY_CURRENT_USER -2147483647L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_LOCAL_MACHINE
#define com_coi_tools_os_win_RegistryImpl_HKEY_LOCAL_MACHINE -2147483646L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_USERS
#define com_coi_tools_os_win_RegistryImpl_HKEY_USERS -2147483645L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_PERFORMANCE_DATA
#define com_coi_tools_os_win_RegistryImpl_HKEY_PERFORMANCE_DATA -2147483644L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_CURRENT_CONFIG
#define com_coi_tools_os_win_RegistryImpl_HKEY_CURRENT_CONFIG -2147483643L
#undef com_coi_tools_os_win_RegistryImpl_HKEY_DYN_DATA
#define com_coi_tools_os_win_RegistryImpl_HKEY_DYN_DATA -2147483642L
/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    exist
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_coi_tools_os_win_RegistryImpl_exist
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    createKeyN
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_win_RegistryImpl_createKeyN
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    setValueN
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/coi/tools/os/win/RegDataContainer;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_win_RegistryImpl_setValueN
  (JNIEnv *, jobject, jint, jstring, jstring, jobject);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getValueType
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coi_tools_os_win_RegistryImpl_getValueType
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Lcom/coi/tools/os/win/RegDataContainer;
 */
JNIEXPORT jobject JNICALL Java_com_coi_tools_os_win_RegistryImpl_getValue
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    deleteValueN
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_win_RegistryImpl_deleteValueN
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    deleteKeyN
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_win_RegistryImpl_deleteKeyN
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    isKeyEmpty
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_coi_tools_os_win_RegistryImpl_isKeyEmpty
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getSubkeyCount
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coi_tools_os_win_RegistryImpl_getSubkeyCount
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getValueCount
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coi_tools_os_win_RegistryImpl_getValueCount
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getSubkeyName
 * Signature: (ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_coi_tools_os_win_RegistryImpl_getSubkeyName
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getValueName
 * Signature: (ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_coi_tools_os_win_RegistryImpl_getValueName
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getSubkeyNames
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_coi_tools_os_win_RegistryImpl_getSubkeyNames
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getValueNames
 * Signature: (ILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_coi_tools_os_win_RegistryImpl_getValueNames
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    getKeyACL
 * Signature: (ILjava/lang/String;)Lcom/coi/tools/os/win/AccessControlList;
 */
JNIEXPORT jobject JNICALL Java_com_coi_tools_os_win_RegistryImpl_getKeyACL
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_coi_tools_os_win_RegistryImpl
 * Method:    modifyKeyACL
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/coi/tools/os/win/AccessControlList;)V
 */
JNIEXPORT void JNICALL Java_com_coi_tools_os_win_RegistryImpl_modifyKeyACL
  (JNIEnv *, jobject, jint, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
